version: '2'
services:
  db:
    image: mysql:5.7
    container_name: first-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
  php:
    image: webdevops/php:7.4
    container_name: first-php
    volumes:
      - "./:/app"
    working_dir: '/app'
  nginx:
    depends_on:
      - php
    image: webdevops/nginx
    container_name: first-nginx
    environment:
      WEB_DOCUMENT_ROOT: /app
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000
    volumes:
      - "./:/app"
    ports:
      - "80:80"